version: "3"
services:
    web:
        container_name: web
        build: ./nginx
        ports:
          - "443:443"
        links:
          - php
        volumes:
          - ./magento:/var/www/magento:cached
    php:
        container_name: php
        build: ./php
        expose:
          - 9000
        volumes:
          - ./magento:/var/www/magento:cached
        depends_on:
          - db
    db:
        container_name: db
        image: mysql:5.7
        ports:
          - "3306:3306"
        expose:
          - 3306
        env_file: .env
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
            timeout: 20s
            retries: 10
    mailhog:
        container_name: mail
        image: mailhog/mailhog:latest
        links:
          - php
        ports:
          - "1025:1025"
          - "8025:8025"
    redis:
        container_name: redis
        image: redis:latest
volumes:
    magento:
