version: "3"
services:
    web:
        build: ./nginx
        ports:
          - "8081:8080"
          - "8443:443"
        links:
          - php
        volumes:
          - ./magento:/var/www/magento:cached
        env_file:
          - .env
    varnish:
      depends_on:
        - web
      build: ./varnish
      links:
        - web
      ports:
        - 6091:6081
        - 6092:6082
    php:
        build: ./php
        expose:
          - 9000
        volumes:
          - ./magento:/var/www/magento:cached
        depends_on:
          - db
        env_file:
          - .env
        environment:
          - XDEBUG_CONFIG=idekey=PHPSTORM
    db:
        image: mariadb:10.4
        ports:
          - "3308:3306"
        expose:
          - 3308
        env_file: .env
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
            timeout: 20s
            retries: 10
    mailhog:
        image: mailhog/mailhog:latest
        links:
          - php
        ports:
          - "1026:1025"
          - "8026:8025"
    redis:
        image: redis:latest
    rabbitmq:
      image: rabbitmq:3.8-management-alpine
      ports:
        - "15672:15672"
        - "5672:5672"
      volumes:
        - rabbitmqdata:/var/lib/rabbitmq
    elasticsearch:
      build: ./es
      ports:
        - "9204:9200"
        - "9304:9300"
      environment:
        "discovery.type": "single-node"
volumes:
    magento: